[project]
name = "dbt-snowflake-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core~=1.9.4",
    "dbt-snowflake~=1.9.2",
]
